### ISSUE TITLE
Research SMART on FHIR Proxy for Azure AD

### ISSUE THREAD

**Issue by briansok71** [CDCgov/data-exchange-fhir#18]
Research SMART on FHIR Proxy for Azure AD to understand capabilities and limitations of this library.

**Comment by DrWatsonofTexas** [comment]
12/16/2022: Watson to confirm with the Microsoft team about this user story's validity of status.

**Comment by mikeschi12** [comment]
Steve Ordhal (prod group) helped me (and the whole team) understand how Smart on FHIR works to Authorize users to different contexts in FHIR.   Microsoft GRAPH API combines scopes from AAD security group RBAC with contexts from FHIR Service in the authenticated claims token.  Diagram drawn.

**Comment by DrWatsonofTexas** [comment]
Completed as of 1/18/2023 per Mike Schimmel.
