### ISSUE TITLE
Configure $export command to filter MedMorph survey data

### ISSUE THREAD

**Issue by briansok71** [CDCgov/data-exchange-fhir#60]
Configure $export command to filter MedMorph survey data, so that correct data is exported to EDAV

**Comment by rmharrison** [comment]
@briansok71 
Stale ticket. Please rewrite to reflect teh business problem
User-defined export from FHIR server (as distinct from the Event-based triggers using Azure Functions)

Options...
- $export
- Logic App
- PRIME FHIR Export GUI
  * GUI proper: 
  * Exporter code for JSON: https://github.com/CDCgov/prime-public-health-data-infrastructure/tree/c1c3683800248938f6e78f3618f5fe316906b6a8/src/FunctionApps/python/FhirServerExport
  * JSON to Table: https://github.com/CDCgov/phdi/blob/main/phdi/tabulation/tables.py
