### ISSUE TITLE
Create logical design for External Person authentication and authorization

### ISSUE THREAD

**Issue by briansok71** [CDCgov/data-exchange-fhir#92]
Create a logical design for external Person authentication and authorization, so that the FHIR solution can authenticate and authorize calls from external users.

**Comment by briansok71** [comment]
DEC-8: The delivery team met with the Product Group to discuss the latest authN/authZ recommendations, including SMART on FHIR support and product roadmap

**Comment by DrWatsonofTexas** [comment]
Mike Schimmel has responded on this user story that Person Auth requires a discussion with a product owner on what the entitlements need to be. Then, a design can be proposed for it by the Microsoft team.

**Comment by DrWatsonofTexas** [comment]
External person authorization is not needed for FY23 Q2 so Watson moved this to the Ice Box. Only machine-to-machine authorization is required for this Phase 1 of the FHIR project.

**Comment by mikeschi12** [comment]
Draft Architecture Drawing on Lucid:  https://lucid.app/lucidchart/bfeea8ed-ad1d-4052-9f9b-a9fc3f758d07/edit?page=vmE9hOIVsmk72&invitationId=inv_8ac32cb4-2d06-4cee-a4ce-1a2d5c5941b6#

**Comment by mikeschi12** [comment]
Visio version of Drawing:  https://microsoft.sharepoint.com/:u:/r/teams/CDCDataModernizationInitiativeDMIINTERNALONLY/_layouts/15/Doc.aspx?sourcedoc=%7B97905E6E-D441-4B32-8D03-A19425B9AF59%7D&file=FHIR%20User%20Auth%20Logical%20Architecture.vsdx&action=default&mobileredirect=true&share=IQFuXpCXQdQyS40DoZQlua9ZAWYQVWFmETJ9oubIXvDeDSg
